### ISSUE TITLE
AUTH for source and target?

### ISSUE THREAD

**Issue by amozgovoy** [BalaclavaLab/blc-redis-dump-restore#1]
Thank you for this project! It would be great if you add -ta and -fa to command line parameters to authenticate against source and target redis.

**Comment by vleushin** [comment]
Hello! I will look into it. I see no problem in adding those.

**Comment by vleushin** [comment]
Hello! I've updated library and documentation. Syntax is a little bit different:
`./blc-redis-dump-restore -f redis://host1/1 -t redis://:password@host2/2`.

More Redis URI syntax examples are here: https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details#uri-syntax
